
spring:
  application:
    name: websocketredis
  rabbitmq:
    host: 111.230.94.160
    port: 5672
    username: wangyuheiyi
    password: f5XocXKtUJFth17PS8bS
  redis:
    host: 111.230.94.160
    port: 6379
    password: f5XocXKtUJFth17PS8bS
    cluster:
      nodes: 111.230.94.160:6379,111.230.94.160:6380,111.230.94.160:6381
    sentinel:
      nodes: 111.230.94.160:26379,111.230.94.160:26380,111.230.94.160:26381
      master: mymaster
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 10 # 连接池中的最大空闲连接 默认 8
        min-idle: 2 # 连接池中的最小空闲连接 默认 0
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        time-between-eviction-runs: 2000 #从池中取出连接前进行检验的校验时长
      shutdown-timeout: 2000
    timeout: 3000
    database: 0
server:
  port: 8081
logging:
  config: classpath:log4j2-spring.xml